### ISSUE TITLE
Button disappears once hash changes

### ISSUE THREAD

**Issue by rene78** [djbooth007/tallycoin#1]
I encountered an issue on Single Page Apps: Whenever the DOM is re-rendered (e.g. by changing the URL hash) tallycoin.js doesn't re-render the donate button. The button simply disappears from the website.

In tallycoin.js below line 3 (`window.onload = function () { tallypay_start(); }`) I added the following code that fixed the issue for me:

```
window.onhashchange = function(){
  setTimeout(function(){
    tallypay_start();
  }, 500);
};
```

The timeout is needed to wait for the re-render.

Here is my specific case: https://github.com/rene78/BitcoinMythBusters/issues/2

**Comment by djbooth007** [comment]
Closing this issue. This version of Tallypay has been deprecated.
