### ISSUE TITLE
ERROR - user not found

### ISSUE THREAD

**Issue by StaceyPEC** [djbooth007/tallycoin#4]
I have set up my Tallycoin account and added the plugin to my website as instructed but on the plugin (and on the preview on the Tallycoin website) it says "ERROR user not found". Please help- how can I fix it?

**Comment by djbooth007** [comment]
The simplest configuration is to add your profile username into the <div> such as

`<div class="tallypay" data-user="StaceyPEC"></div>`

Make sure data-user is your Tallycoin username.

**Comment by StaceyPEC** [comment]
Hello,

Thank you for your response. I have tried that. And I tried using my email
address as my username as well. It still says user not found.

Kind Regards,
<http://pristinecollective.com/> *Stacey Cyrus* M.Sc.; Environmental
Adviser

*e. ***@***.***
*m. *+27 82 951 4574

pristinecollective.com
