### ISSUE TITLE
CSS not available anymore?

### ISSUE THREAD

**Issue by rene78** [djbooth007/tallycoin#5]
The tallypay donate buttons on my websites are no longer appearing. Looks like as if the link https://tallyco.in/css/tallypay.css?v=2.1.4 is dead.

**Comment by djbooth007** [comment]
Hi Rene, this version of Tallypay has been deprecated. I put a notice on the readme file.
The latest version is available at https://tallycoin.app/plugin/

The new code is very similar so you shouldn't need to change much on your website, however you will need to make a few small changes.
